api/urls.py
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .views import (AssignmentCreate, AssignmentDetail, AssignmentList,
                    ClassroomCreateView, ClassroomDetail, ClassroomJoinView,
                    ClassroomList, FeedBackView, JudgeCode, PlagiarismReport,
                    PlagiarismView, ProfessorDetail, ProfessorSignupView,
                    ProfessorViewSet, QuestionCreate, QuestionDetail,
                    QuestionList, ReportQuesiton, StudentDetail,
                    StudentSignupView, StudentViewSet, SubmissionCreate,
                    SubmissionDetail, SubmissionList, UserLoginView,
                    UserLogoutView)

schema_view = get_schema_view(
   openapi.Info(
      title="CodeClassroom API",
      default_version='v2.1.0',
      description="A platform for managing programming assignments in colleges & universities.",
      contact=openapi.Contact(email="varshneybhupes@gmail.com"),
      license=openapi.License(name="AGPL-3.0"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


student_list = StudentViewSet.as_view({'get': 'list'})
student_detail = StudentViewSet.as_view({'get': 'retrieve'})

professor_list = ProfessorViewSet.as_view({'get': 'list'})
professor_detail = ProfessorViewSet.as_view({'get': 'retrieve'})


urlpatterns = [
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('signup/professor', ProfessorSignupView.as_view(), name='prof-signup'),
    path('signup/student', StudentSignupView.as_view(), name='student-signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),

    path('students', student_list, name='students'),
    path('students/<int:pk>', StudentDetail.as_view(), name='student'),
    path('professors', professor_list, name='professors'),
    path('professors/<int:pk>', ProfessorDetail.as_view(), name='professor'),

    # All Classroom URLs
    path('classrooms/create', ClassroomCreateView.as_view(), name='classroom-create'),
    path('classrooms/join', ClassroomJoinView.as_view(), name='classroom-join'),
    path('classrooms/<int:pk>', ClassroomDetail.as_view(), name='classroom-detail'),
    path('classrooms', ClassroomList.as_view(), name='classrooms'),

    # All Assignment URLs
    path('assignments/create', AssignmentCreate.as_view(),
         name='assignment-create'),
    path('assignments', AssignmentList.as_view(), name='assignment-list'),
    path('assignments/<int:pk>', AssignmentDetail.as_view(), name='assignment-list'),

    # All Question URLs
    path('questions/create', QuestionCreate.as_view(), name='question-create'),
    path('questions', QuestionList.as_view(), name='question-list'),
    path('questions/<int:pk>', QuestionDetail.as_view(), name='question-detail'),

    # All Solution/Submission URLs
    path('submissions/create', SubmissionCreate.as_view(), name='submission-create'),
    path('submissions/<int:pk>', SubmissionDetail.as_view(), name='submissions-detail'),
    path('submissions', SubmissionList.as_view(), name='submissions'),

    # Utility URLs
    path('judge', JudgeCode.as_view(), name='code-judge'),
    path('codesim', PlagiarismView.as_view(),
         name='plagiarism-detector'),
    path('email/feedback', FeedBackView.as_view(), name='feedback'),
    path('email/report', ReportQuesiton.as_view(), name='report-question'),
    path('email/plagiarism-report', PlagiarismReport.as_view(), name='report-plagiarism')

]

app/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.urls import include, path, reverse_lazy
from . import views

app_name = 'app'
urlpatterns = [
    path('api/', include('api.urls')),

    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='app/login.html',
        extra_context={
            'title': 'Login',
            'form': AuthenticationForm(auto_id=True),
        },
    ), name='login'),
    path('logout/', login_required(auth_views.LogoutView.as_view(
        template_name='app/logout.html',
        extra_context={
            'title': 'Logout'
        },
    )), name='logout'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),

    # classroom views
    path('classrooms/', views.classrooms, name='classrooms'),
    path('classrooms/<int:pk>', views.classroom, name='classroom'),
    path('classrooms/<int:pk>/edit', views.edit_classroom, name='edit-classroom'),
    path('classrooms/<int:pk>/delete', views.delete_classroom, name='delete-classroom'),
    path('classrooms/join/', views.join_classroom, name='join-classroom'),


    # assignment views
    path('assignments/', views.assignments, name='assignments'),
    path('assignment/<int:pk>', views.assignment, name='assignment'),
    path('assignment/<int:pk>/edit', views.edit_assignment, name='edit-assignment'),
    path('assignment/<int:pk>/delete', views.delete_assignment, name='delete-assignment'),

    # question views
    path('question/<int:pk>', views.question, name='question'),
    path('question/<int:pk>/edit', views.edit_question, name='edit-question'),
    path('question/<int:pk>/delete', views.delete_question, name='delete-question')

]

codeclassroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
]

admin.site.site_header = "CodeClassroom Administration"
admin.site.site_title = "CodeClassroom Admin"

# for serving media files during development, taken from Django documentation
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,height=device-height, initial-scale=1.0, shrink-to-fit=yes">
    <!-- redirect http resources to https, hopefully! -->
    <!-- <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> -->
    <!-- CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'app/css/materialize.min.css' %}" media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/css/codemirror.css' %}">
    <!-- Scripts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="screen" />
    <script defer src="https://use.fontawesome.com/releases/v4.7.0/js/all.js"></script>
    {% block link %}
    {% endblock link %}
    {% if title %}
      <title>{{ title }} - CodeClassroom</title>
    {% else %}
      <title>{% block title %}{% endblock %}</title>
    {% endif %}
  </head>
  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a data-position="bottom" data-tooltip="defe" href="{% url 'app:index' %}" class="brand-logo tooltipped">
            CodeClassroom
          </a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'app:about' %}">About</a></li>
            <li><a href="{% url 'app:faq' %}">FAQ</a></li>
            {% if request.user.is_authenticated %}
              <li><a href="#{# {% url 'app:dashboard' %} #}">Dashboard</a></li>
              <li><a href="{% url 'app:logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'app:login' %}">
              Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>

    {% block content %}
      {% block messages %}
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endblock messages %}
    {% endblock content %}
    {% block js %}
    {% endblock js %}

    <!-- IDE Themes -->
    <link rel="stylesheet" href="{% static 'app/css/theme/abcdef.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/base16-light.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/blackboard.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/cobalt.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/colorforth.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/monokai.css' %}">

    <script defer type="text/javascript" src="{% static 'app/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/materialize.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.5/lib/darkmode-js.min.js"></script>
    <script src="{% static 'app/js/codemirror.js'%}"></script>

    <!--CodeMirror Modes -->
    <script src="{% static 'app/js/mode/clike/clike.js'%}"></script>
    <script src="{% static 'app/js/mode/python/python.js'%}"></script>
    <script src="{% static 'app/js/mode/shell/shell.js'%}"></script>
    <script>
    function getMode () {
        const lang = document.getElementById("language").innerHTML;
        var c_like_langs = ["C", "C++", "Java"]
        if (lang == "Python3"){
          mode = "python"
        }
        else if (c_like_langs.includes(lang)){
          mode = "clike"
        }
        else if (lang == "Bash"){
          mode = "shell"
        }
        return mode
    }
    var code_editor = document.getElementById("editor");
    if (code_editor !== null){
      console.log("here");
      var editor = CodeMirror.fromTextArea(code_editor, {
        lineNumbers: true,
        styleActiveLine: true,
        matchBrackets: true,
        mode: getMode()
      });
    }
    function selectTheme(){
      var input = document.getElementById("theme-select");
      var theme = input.options[input.selectedIndex].textContent;
      editor.setOption("theme", theme);
      location.hash = "#" + theme;
    }
    </script>
  </body>
</html>

app/templates/app/cc-assignments.html
{% extends 'app/cc-base-dashboard.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/assignments.css' %}">
{% endblock link %}

{% block content %}
<h2>Assignments</h2>

{% block messages %}
{{ block.super }}
{% endblock messages %}

<section id="assignments">
  {% if assignments %}
  <section id="header">
    <strong>Name</strong>
    <strong>Classroom</strong>
    <strong>Language</strong>
  </section>
  {% endif %}
  <section id="body">
    <!-- TODO: add triple dot SVG -->
    {% for assignment in assignments %}
    <a href="{% url 'app:assignment' assignment.pk %}">
      <div class="assignment">
        <p>{{ assignment.title }}</p>
        <p>{{ assignment.classroom.title }}</p>
        <p>{{ assignment.language }}</p>
      </div>
    </a>
    {% if professor %}
    <strong>:</strong>
    <div class="actions">
      <a href="{% url 'app:edit-assignment' assignment.pk %}">Edit</a>
      <a id="delete-button" href="{% url 'app:delete-assignment' assignment.pk %}">Delete</a>
    </div>
    {% endif %}
    {% empty %}
    <p>No assignments yet!</p>
    {% endfor %}
  </section>
</section>
{% endblock content %}

{% block form %}
<form method="POST" action="{% url 'app:assignments' %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="submit" value="Create New Assignment">
</form>
{% endblock form %}

{% block svg %}
{{ block.super }}
{% endblock svg %}

{% block js %}
{{ block.super }}
{% if professor %}
<script type="text/javascript">
  const optionButtons = document.querySelectorAll('#body > strong');
  for (optionButton of optionButtons) {
    const actions = optionButton.nextElementSibling;
    optionButton.addEventListener('click', (e) => {
      e.stopPropagation();
      if (!actions.style.display) {
        actions.style.display = 'flex';

      } else {
        actions.style.display = '';
      }
    });
  }
</script>
<!-- Delete prompt text -->
<script id="delete-question" type="application/json">
  {"question":"Delete Assignment?"}
</script>
{% endif %}
{% endblock js %}

app/templates/app/cc-base-dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,height=device-height, initial-scale=1.0, shrink-to-fit=yes">
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/base-dashboard.css' %}">
  {% block link %}
  {% endblock link %}
  <title>CodeClassroom - {{ title }}</title>
</head>
<body>
  <header>
    <h1>
      <a href="{% url 'app:index' %}">Code Classroom</a>
    </h1>
    <nav>
      <ul>
        <li>
          <a href="#">Profile</a>
        </li>
        <li>
          <a href="#">Notifications</a>
        </li>
        <li>
          <a href="/logout">Logout</a>
        </li>
      </ul>
    </nav>
  </header>
  <aside>
    <figure>
      <img src="https://via.placeholder.com/125" width="125" height="125">
      <figcaption>{{ request.user.username }}</figcaption>
    </figure>
    <nav>
      <ul>
        <li>
          <a href="{% url 'app:classrooms' %}"{% if active_link == 'classrooms' %} style="font-weight: bold;"{% endif %}>Classrooms</a>
        </li>
        <li>
          <a href="{% url 'app:assignments' %}"{% if active_link == 'assignments' %} style="font-weight: bold;"{% endif %}>Assignments</a>
        </li>
        <li>
          <a href="#">Projects</a>
        </li>
        <li>
          <a href="#">Contact Us</a>
        </li>
        <li>
          <a href="#">Help</a>
        </li>
      </ul>
    </nav>
  </aside>
  <main>
    {% block content %}
    {# flash messages to be handled by child templates inside content block #}
    {% block messages %}
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    {% endblock messages %}
    {% endblock content %}
  </main>
  {% if add %}
  <div id="add">
    <svg>
      <use href="#plus-sign"/>
    </svg>
  </div>
  {% block form %}
  {% endblock form %}
  {% endif %}
  {% block svg %}
  <svg style="display: none;">
    <defs>
      <path id="plus-sign" d="M 8.7568897,17.38827 H 17.261354 V 8.782562 0.17685486 h 2.733578 2.733576 V 8.782562 17.38827 h 8.504463 8.504462 v 2.632336 2.632335 h -8.504462 -8.504463 v 8.504466 8.504465 H 19.994932 17.261354 V 31.157407 22.652941 H 8.7568897 0.25242584 V 20.020606 17.38827 Z M 0.1511788,17.287028 H 39.838679 v 5.467157 H 0.15117853 Z M 22.829753,0.07561026 V 39.76311 H 17.160112 V 0.07561026 Z"></path>
    </defs>
  </svg>
  {% endblock svg %}
  {% block js %}
  {% if add %}
  <script type="text/javascript">
    // show form on clicking add button
    document.querySelector('#add').addEventListener('click', (e) => document.querySelector('form').classList.toggle('show'));
  </script>
  {% endif %}
  {% if delete %}
  <script type="text/javascript">
    // prompt confirmation for deletion
    const deleteButton = document.querySelector('#delete-button')
    deleteButton.addEventListener('click', (event) => {
      event.preventDefault()
      // get question
      const question = JSON.parse(document.getElementById('delete-question').textContent).question

      // confirm deletion
      const answer = window.confirm(question)
      if (answer) {
        window.location.href = deleteButton.href;
      }
    })
  </script>
  {% endif %}
  {% endblock js %}
</body>
</html>

app/templates/app/cc-classroom.html
{% extends 'app/cc-base-dashboard.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/classroom.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock link %}

{% block content %}
<section id="classroom">
  <div>
    <h2>{{ classroom.title }}</h2>
    {% if professor %}
    <div id="actions">
      <a href="{% url 'app:edit-classroom' classroom.pk %}">
        Edit Classrooom
      </a>
      <a id="delete-button" href="{% url 'app:delete-classroom' classroom.pk %}">
        Delete Classroom
      </a>
    </div>
    {% endif %}
  </div>
  <p>Professor: {{ classroom.professor }}</p>
  {% if professor %}
  <p>Join Code: {{ classroom.join_code }}</p>
  {% endif %}
</section>

{% block messages %}
{{ block.super }}
{% endblock messages %}

<section id="assignments">
  <h3>Assignments</h3>
  <ul>
    {% for assignment in assignments %}
    <li>
      <a href="{% url 'app:assignment' assignment.pk %}">
        <div class="assignment">
          <h3>{{ assignment.title }}</h3>
          <p>Deadline: {{ assignment.deadline }}</p>
          <p>Language of focus: {{ assignment.language }}</p>
        </div>
      </a>
    </li>
    {% empty %}
    <h3>No assignments yet!</h3>
    {% endfor %}
  </ul>
</section>

<section id="students">
  <h3>Students</h3>
  <ol>
    {% for student in students %}
    <li>
      {{ student.user.username }}
    </li>
    {% empty %}
    <h3>No students yet!</h3>
    {% endfor %}
  </ol>
</section>
{% endblock content %}

{% block form %}
<form action="{% url 'app:classroom' classroom.pk %}" method="POST">
  <h2>Create Assignment</h2>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Add Assignment">
</form>
{% endblock form %}

{% block js %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script type="text/javascript">
  flatpickr('#deadline', {
  enableTime : true,
  enableSeconds : true,
  dateFormat : "Y-m-d H:i:S",
  });
</script>
<!-- Delete prompt text -->
<script id="delete-question" type="application/json">
  {"question":"Delete Classroom?"}
</script>
{% endblock js %}

app/templates/app/cc-index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/index.css' %}">
  <title>Code Classroom</title>
</head>
<body>
  <header>
    <h1>
      <a href="{% url 'app:index' %}">Code Classroom</a>
    </h1>
    <nav>
      <ul>
        <li>
          <a href="{% url 'app:about' %}">About Us</a>
        </li>
        <li>
          <a href="#">Contact</a>
        </li>
        <li>
          <a href="#">Help</a>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    <section id="cta">
      <!-- Call to action section -->
      <h2>A great place for all your programming assignments!</h2>
      <p>A platform for management of programming assignments in universities and schools.</p>
    </section>
    <aside id="login-sign-up">
      <a href="{% url 'app:login' %}">Login</a>
      <a class="button" href="{% url 'app:signup' %}">Sign-Up</a>
    </aside>
    {% endblock content %}
  </main>
</body>
</html>

app/templates/app/cc-question.html
{% extends 'app/cc-base-dashboard.html' %}
{% load static %}

{% block link %}
  {% if student %}
    <link rel="stylesheet" href="{% static 'app/css/codemirror.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/abcdef.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/base16-light.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/blackboard.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/cobalt.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/theme/colorforth.css' %}">
  {% endif %}
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/question.css' %}">
{% endblock link %}

{% block content %}
  <div>
    <h2>{{ question.title }}</h2>
    <div id="language">
      {{ question.assignment.language }}
    </div>
    {% if professor %}
      <div id="actions">
        <a href="{% url 'app:edit-question' question.pk %}">Edit Question</a>
        <a id="delete-button" href="{% url 'app:delete-question' question.pk %}">Delete Question</a>
      </div>
    {% endif %}
  </div>

  {% block messages %}
    {{ block.super }}
  {% endblock messages %}

  <div id="question">
    <section>
      <h3>Question</h3>
      <p>{{ question.description }}</p>
    </section>
    <section>
      <h3>Sample Input</h3>
      <p>
        {% if question.sample_input %}
          {{ question.sample_input|linebreaksbr }}
        {% else %}
          No input.
        {% endif %}
      </p>
    </section>
    <section>
      <h3>Sample Output</h3>
      <p>{{ question.sample_output|linebreaksbr }}</p>
    </section>
    {% if professor %}
      <h4>Marked for draft</h4>
      <p>{{ question.draft }}</p>
    {% endif %}
  </div>
  {# IDE goes here #}
  {% if student %}
    <div id="IDE">
      <p>Select Theme</p>
      <select onchange="selectTheme()" id="theme-select">
        <option selected="">default</option>
        <option>abcdef</option>
        <option>base16-light</option>
        <option>blackboard</option>
        <option>cobalt</option>
        <option>colorforth</option>
        <option>monokai</option>
      </select>
      <textarea id="editor"></textarea>
      <button id="run" onclick="judge_code(
      '{{ question.id }}', '{{ question.assignment.language }}')">Run</button>
      <button id="submit" disabled onclick="submit_code(
      {{ question.id }}, {{ student.id }}, {{ assignment.id }})">Submit</button>
    </div>
    <div id="execution">
    </div>
  {% endif %}
{% endblock content %}

{% block form %}
{% endblock form %}

{% block js %}
  {{ block.super }}
  {% if student %}
    <script defer type="text/javascript" src="{% static 'app/script.js' %}"></script>
    <script src="{% static 'app/js/codemirror.js'%}"></script>
    <!--CodeMirror Modes -->
    <script src="{% static 'app/js/mode/clike/clike.js'%}"></script>
    <script src="{% static 'app/js/mode/python/python.js'%}"></script>
    <script src="{% static 'app/js/mode/shell/shell.js'%}"></script>
    <script>
    function getMode () {
      // Used for changing the Syntax coloring according to language
      const lang = document.getElementById("language").innerText;
      var c_like_langs = ["C", "C++", "Java"]
      if (lang == "Python3"){
        mode = "python"
      }
      else if (c_like_langs.includes(lang)){
        mode = "clike"
      }
      else if (lang == "Bash"){
        mode = "shell"
      }
      return mode
    }
    var code_editor = document.getElementById("editor");
    if (code_editor !== null){
      var editor = CodeMirror.fromTextArea(code_editor, {
      lineNumbers: true,
      styleActiveLine: true,
      matchBrackets: true,
      mode: getMode()
      });
    }
    function selectTheme(){
      var input = document.getElementById("theme-select");
      var theme = input.options[input.selectedIndex].textContent;
      editor.setOption("theme", theme);
      location.hash = "#" + theme;
    }
    </script>
    <script id="delete-question" type="application/json">
    {"question":"Delete Question?"}
    </script>
  {% endif %}
{% endblock js %}

app/templates/app/edit-classroom.html
{% extends 'app/cc-base-dashboard.html' %}
{% load static %}
{% block content %}
	<form style="display: block" action="{% url 'app:edit-classroom' pk %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="submit" value="Update Question">Update Classroom</button>
	</form>
{% endblock content %}

app/templates/app/login.html
{% extends 'app/cc-index.html' %}
{% load static %}
{% block content %}
	{% block messages %}
		{{ block.super }}
	{% endblock messages %}
	<div id="layout">
		<div id="form">
			<form action="{% url 'app:login' %}" method="POST">
				{% csrf_token %}
				<input type="text" name="username" placeholder="Email or User Name">
				<input type="password" name="password" placeholder="Password">
				<a href="forgotpassword.html">Forgot Password?</a>
				<input id="formlgnbtn" type="submit" value="Login">
				<div>
					<p>Not on CodeClassromm</p>
					<button><a href="{% url 'app:signup' %}">Signup</a></button>
				</div>
			</form>
		</div>
		<div id="intro">
			<h1>A great place for all your projects and assignments!</h1>
			<p>A platform for the management of Programming assignments and projects in Universities/Schools.</p>
		</div>
	</div>
{% endblock content %}
{% block js %}
	<script type="text/javascript" src="{% static 'app/login.js' %}"></script>
{% endblock js %}

app/templates/app/signup.html
{% extends 'app/cc-index.html' %}
{% load static %}
{% block content %}
	{% block messages %}
		{{ block.super }}
	{% endblock messages %}
		<div id="layout">
			<div id="form">
				<form action="{% url 'app:signup' %}" method="POST">
					{% csrf_token %}
					<input type="text" name="username" maxlength="150" autofocus="" required="" id="username" placeholder="username">
					<input type="email" name="email" maxlength="254" id="email" placeholder="email">
					<label for="user_type_0"><input type="radio" name="user_type" value="professor" required="" id="user_type_0">Professor</label>
					<label for="user_type_1"><input type="radio" name="user_type" value="student" required="" id="user_type_1">
					Student</label>
					<!--
					<input type="radio" name="user_type" value="Teacher" onclick="document.getElementById('TCode').style.display='block'"><font size="2pt"> Teacher</font>-->
					<!--
					<input type="radio" name="user_type" value="Student" onclick="document.getElementById('TCode').style.display='none'" checked><font size="2pt"> Student</font><br>
					<span id="TCode" style="display: none;"><input type="text" name="TeacherCode" placeholder="eg. #54cef9" size="7" maxlength="7"><small> Enter identity code</small></span>-->

					<input type="password" name="password1" required="" id="password1" placeholder="Enter Password">

					<label for="password2">Password confirmation:</label> <input type="password" name="password2" required="" id="password2"> <span class="helptext">Enter the same password as before, for verification.</span>

					<input id="formsignupbtn" type="submit" value="Create An Account">

					<div>
						<p>Already have an account ?</p>
						<button><a href="{% url 'app:login' %}">Login</a></button>
					</div>
				</form>
			</div>
			<div id="intro">
				<h1>A great place for all your projects and assignments!</h1>
				<h2>Real Education. Real Results.</h2>
				<p>A platform for the management of Programming assignments and projects in Universities/Schools.</p>
			</div>
{% endblock content %}
{% block js %}
	<script type="text/javascript" src="{% static 'app/signup.js' %}"></script>
{% endblock js %}